### API
GET http://localhost:8080/api/events?page=2020_March_10

### Feed

GET http://localhost:8080/feed/json?subscribe=123

### Metrics

GET http://localhost:8080/metrics

### Fly.io

GET https://wikinewsfeed.fly.dev/feed/json?subscribe=123

### WikiNewsFeed.org

GET https://wikinewsfeed.org/api/events?page=2020_March_10

### WikiNewsFeed.org

GET https://wikinewsfeed.org/feed/rss
